<?php

$dictionary['acl_fields'] = array(
	'table'=>'acl_fields',
	'audited'=>true,
	'fields'=>array (
  'category' => 
  array (
    'required' => '1',
    'name' => 'category',
    'vname' => 'LBL_CATEGORY',
    'type' => 'varchar',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '25',
    'options' => 'moduleList',
  ),
  'aclaccess' => 
  array (
    'required' => false,
    'name' => 'aclaccess',
    'vname' => 'LBL_ACLACCESS',
    'type' => 'enum',
    'dbType' => 'int',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '3',
    'disable_num_format' => '',
    'required' => '1',
    'options' => 'fields_access_list',
  ),
  'role_id' => 
  array (
    'required' => false,
    'name' => 'role_id',
    'vname' => 'LBL_ROLE',
    'type' => 'id',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => 0,
    'audited' => 0,
    'reportable' => 0,
    'len' => 36,
    'options' => 'roles_list',
    'required' => '1',
  ),
  'role' => 
  array (
    'required' => false,
    'source' => 'non-db',
    'name' => 'role',
    'vname' => 'LBL_ROLE',
    'type' => 'relate',
    'massupdate' => 0,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => 0,
    'reportable' => 0,
    'len' => '255',
    'id_name' => 'role_id',
    'ext2' => 'roles',
    'module' => 'ACLRoles',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
  ),
),
	'relationships'=>array (
),
	'optimistic_lock'=>true,
);
require_once('include/SugarObjects/VardefManager.php');
VardefManager::createVardef('acl_fields','acl_fields', array('basic'));
